#!/usr/bin/env Rscript
# Generate a JSON reference of catR's output (nextItem MFI, thetaEst EAP,
# semTheta EAP, plus BM/ML/WL estimation variants and bOpt selection) for
# simulated participants on an item bank.
#
# This is the "ground truth" that the Python port in catpie must reproduce.
# The committed reference in reference/catr_reference.json was generated by
# this script (with the real R catR package) for the EWM item bank.
#
# Usage:
#   Rscript scripts/generate_reference.R /path/to/itembank.csv
# where itembank.csv has columns: discrimination, difficulty, guessing, inattention
#
# Requirements: R with the `catR` and `jsonlite` packages installed.

args <- commandArgs(trailingOnly = TRUE)
itembank_csv <- if (length(args) >= 1) args[1] else
  "assets/csv/itembank.csv"
out_json     <- "reference/catr_reference.json"

stopifnot(file.exists(itembank_csv))
cat("Reading item bank from:", itembank_csv, "\n")

suppressMessages(library(catR))
suppressMessages(library(jsonlite))

df <- read.csv(itembank_csv)
# catR item matrix: (a, b, c, d)
bank <- as.matrix(df[, c("discrimination", "difficulty", "guessing", "inattention")])
colnames(bank) <- c("a", "b", "c", "d")
n_items <- nrow(bank)
cat(sprintf("Item bank: %d items, %d columns\n", n_items, ncol(bank)))

# 4PL probability of a correct response at ability th (catR's Pi).
p_correct <- function(th, par) {
  Pi(th, rbind(par), D = 1)$Pi
}

# Simulate one adaptive run of up to max_items items.
simulate_run <- function(true_theta, seed, max_items = 20) {
  set.seed(seed)
  administered <- integer(0)   # 1-indexed catR indices
  responses    <- integer(0)
  steps <- list()

  for (k in 1:max_items) {
    theta_used <- if (k == 1) 0.0 else steps[[k - 1]]$theta

    # --- Item selection (exactly like the experiment's select_next_item_catr)
    nxt <- nextItem(
      itemBank = bank,
      theta    = theta_used,
      out      = administered,     # NULL-equivalent when empty
      x        = responses,
      criterion = "MFI"
    )
    selected <- nxt$item          # 1-indexed
    info_vec <- as.numeric(Ii(theta_used, bank, D = 1)$Ii)

    # --- Simulate a response at the true ability
    p <- p_correct(true_theta, bank[selected, ])
    r <- rbinom(1, 1, p)

    administered <- c(administered, selected)
    responses    <- c(responses, r)

    # --- Ability estimation (exactly like the experiment's estimate_theta_catr)
    theta <- thetaEst(it = bank[administered, , drop = FALSE],
                      x = responses, method = "EAP")
    se <- semTheta(thEst = theta, it = bank[administered, , drop = FALSE],
                   x = responses, method = "EAP")

    # --- Additional estimation methods / priors (for parity testing)
    est_one <- function(m, pd = "norm") {
      th <- thetaEst(it = bank[administered, , drop = FALSE],
                     x = responses, method = m, priorDist = pd)
      s <- semTheta(thEst = th, it = bank[administered, , drop = FALSE],
                    x = responses, method = m, priorDist = pd)
      list(theta = as.numeric(th), se = as.numeric(s))
    }
    estimates <- list(
      EAP_norm    = est_one("EAP", "norm"),
      BM_norm     = est_one("BM", "norm"),
      ML_norm     = est_one("ML", "norm"),
      WL_norm     = est_one("WL", "norm"),
      EAP_unif    = est_one("EAP", "unif"),
      EAP_jeffreys = est_one("EAP", "Jeffreys")
    )

    # --- bOpt selection (for parity testing)
    nxt_bopt <- nextItem(
      itemBank = bank, theta = theta_used, out = administered,
      x = responses, criterion = "bOpt"
    )

    steps[[k]] <- list(
      step             = k,
      true_theta       = true_theta,
      administered0    = as.integer(administered) - 1L,     # 0-indexed
      responses        = as.integer(responses),
      theta_used       = theta_used,
      selected0        = as.integer(selected) - 1L,         # 0-indexed
      info             = info_vec,
      bopt0            = as.integer(nxt_bopt$item) - 1L,    # 0-indexed
      theta            = as.numeric(theta),
      se               = as.numeric(se),
      estimates        = estimates,
      p_true           = p
    )
  }
  steps
}

true_thetas <- c(-2.0, -1.0, 0.0, 1.0, 2.0)
seeds <- 101:105   # 5 seeds per theta level
max_items <- 20

runs <- list()
for (tt in true_thetas) {
  for (seed in seeds) {
    runs[[length(runs) + 1]] <- list(true_theta = tt, seed = seed,
                                     steps = simulate_run(tt, seed, max_items))
  }
}

cat(sprintf("Simulated %d runs x %d steps.\n",
            length(runs), length(runs[[1]]$steps)))

ref <- list(
  r_version     = paste(R.version$major, R.version$minor, sep = "."),
  catr_version  = as.character(packageVersion("catR")),
  n_items       = n_items,
  itembank      = unname(bank),
  runs          = runs
)

dir.create(dirname(out_json), showWarnings = FALSE, recursive = TRUE)
write_json(ref, out_json, digits = 16, auto_unbox = TRUE)
cat("Wrote reference to:", out_json, "\n")
